services:
  db:
    build: ./sql
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql/products.sql:/docker-entrypoint-storedb.d/products.sql
      - ./sql/users.sql:/docker-entrypoint-storedb.d/users.sql
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=store_management
      - POSTGRES_PORT=5432
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - db

networks:
  default:
    name: app-network