package helpers

const (
	POSTGRES_HOST     = "POSTGRES_HOST"
	POSTGRES_PORT     = "POSTGRES_PORT"
	POSTGRES_USER     = "POSTGRES_USER"
	POSTGRES_PASSWORD = "POSTGRES_PASSWORD"
	POSTGRES_DB       = "POSTGRES_DB"
	JWT_KEY           = "JWT_KEY"
	ACCESS_TOKEN      = "access_token"
	REFRESH_TOKEN     = "refresh_token"
	REDIS_HOST        = "REDIS_HOST"
	REDIS_PORT        = "REDIS_PORT"
	SMTP_HOST         = "SMTP_HOST"
	SMTP_PORT         = "SMTP_PORT"
	SMTP_USER         = "SMTP_USER"
	SMTP_PASSWORD     = "SMTP_PASSWORD"
)
